### ISSUE TITLE
Change DB driver from mongoDb-driver to mongoose

### ISSUE THREAD

**Issue by vivekshah1801** [LockedUp-Coders/nostalgify#14]
- [ ] remove the mongo-db driver
- [ ] add mongoose

**Comment by harshil15999** [comment]
please assign this to me

**Comment by tanay13** [comment]
Can you specify the folder in which we have to make changes?

**Comment by vivekshah1801** [comment]
@tanay13 Database folder

**Comment by vivekshah1801** [comment]
@YashKumarVerma looks like the modules/database folder is deleted in master.
where should put the database connection code?

Note:
I have written the code according to the previous modules/database folder.
