### ISSUE TITLE
New feature proposal:User Registration

### ISSUE THREAD

**Issue by vivekshah1801** [LockedUp-Coders/nostalgify#19]
Child of #17

What I Plan to do:
- [ ] get data from req.body
- [ ] validate it, if not proper return err in json
- [ ] if user exists return err in json
- [ ] store in Db
- [ ] return success in json.

@YashKumarVerma

**Comment by YashKumarVerma** [comment]
Don't return success in .json. Return the newly created user's detail.

**Comment by vivekshah1801** [comment]
okay. noted.
