### ISSUE TITLE
Template Cleanup

### ISSUE THREAD

**Issue by YashKumarVerma** [LockedUp-Coders/nostalgify#2]
Remove content related to template which is not needed in our project. For eg. Badges pointing to a different repository.

**Comment by harshil15999** [comment]
assign it to me

**Comment by harshil15999** [comment]
In this what all has to be changed ?Could you please explain it to me a bit more elaborately

**Comment by YashKumarVerma** [comment]
> In this what all has to be changed ?Could you please explain it to me a bit more elaborately

Badges pointing to a different repository.
