### ISSUE TITLE
New feature proposal:Login Page

### ISSUE THREAD

**Issue by VershaCoder** [LockedUp-Coders/nostalgify#20]
Child of #18 

HTML preview : [https://codepen.io/versha/pen/GRoqQWa](https://codepen.io/versha/pen/GRoqQWa)
Login Page Layout Code :(https://github.com/VershaCoder/FrontEndTasks/blob/master/UpdatedLoginPage.html)

@YashKumarVerma

**Comment by YashKumarVerma** [comment]
Use Github pages / codepen / any other service to show the layout.

**Comment by YashKumarVerma** [comment]
tip: use layout similar to #21

**Comment by VershaCoder** [comment]
@YashKumarVerma  I have updated the layout and added a link for layout preview.

**Comment by YashKumarVerma** [comment]
There are instructions given on the parent issue of this issue about the changes that are to done and steps to be followed while doing a submission. Kindly check them out, and submit the work.

**Comment by VershaCoder** [comment]
Okay, I'll check it out.
