### ISSUE TITLE
New feature Proposal: SignUp page

### ISSUE THREAD

**Issue by hayat-tamboli** [LockedUp-Coders/nostalgify#21]
child issue of #18 

HTML layout(code): https://github.com/hayat-tamboli/frontend-work/blob/master/SignUp.html

HTML preview: https://hayat-tamboli-frontend-work.glitch.me/SignUp.html

**Comment by YashKumarVerma** [comment]
Use Github pages / codepen / any other service to show the layout.

**Comment by YashKumarVerma** [comment]
@hayat-tamboli 

Few changes:
1. remove navbar
2. Make sure image is copyright free 
3. Move the input form inside a card
4. use`<small>` styling or similar for the line: `already have an account? Log In`
5. Change text : SignUp to something more interactive.

**Comment by hayat-tamboli** [comment]
made all changes 
-  same [codebase](https://github.com/hayat-tamboli/frontend-work/blob/master/SignUp.html)
-  same [preview site](https://hayat-tamboli-frontend-work.glitch.me/SignUp.html)
-  the image is from [Undraw](https://undraw.co/license) so it is copywrite free

@YashKumarVerma tell me if any other changes are needed.

**Comment by YashKumarVerma** [comment]
@hayat-tamboli 

- create a folder named reference
- create folder named reference/assets/
- create folder named reference/assets/css
- create folder named reference/assets/js
- create folder named reference/assets/images
- make sure you put all the css , js, image files your code depends on in the css , js, image folder.
- make sure your code does not use CDN and use these local files.

**Comment by hayat-tamboli** [comment]
> @hayat-tamboli
> 
> * create a folder named reference
> * create folder named reference/assets/
> * create folder named reference/assets/css
> * create folder named reference/assets/js
> * create folder named reference/assets/images
> * make sure you put all the css , js, image files your code depends on in the css , js, image folder.
> * make sure your code does not use CDN and use these local files.

should I make that folder in src or root

**Comment by YashKumarVerma** [comment]
Instructions posted in https://github.com/LockedUp-Coders/nostalgify/issues/18
