### ISSUE TITLE
New feature Proposal : User login and logout

### ISSUE THREAD

**Issue by tanay13** [LockedUp-Coders/nostalgify#22]
Child of #17 

What i plan to do is 
* using local strategy of passport i will authenticate the username and password that the user is entering
* If it is valid details then i will redirect the page to user profile and if its a failure then i will redirect it again to /login page
* for logout i will use req.logout() and will redirect it to the home page

**Comment by YashKumarVerma** [comment]
You'll have to setup passport for this project.

**Comment by tanay13** [comment]
yes i will do it

**Comment by YashKumarVerma** [comment]
updates ?

**Comment by tanay13** [comment]
@YashKumarVerma I have sent the PR .
 Should i delete the previous PR i had sent?

**Comment by YashKumarVerma** [comment]
Ensure that only one active PR is there for one issue.

**Comment by tanay13** [comment]
@YashKumarVerma  Okay i will keep that in mind
