### ISSUE TITLE
New Feature:Error Page 

### ISSUE THREAD

**Issue by PrachiSinghal86** [LockedUp-Coders/nostalgify#26]
- Child #18
- A normal bootstrap page with error 404 written on it.
- and then there can be a go-to homepage button 
- Later we can add a lightweight game

**Comment by YashKumarVerma** [comment]
1. Show the layout of the page , preview link.
2. Make the error page general so that we can use it for other errors as well.

**Comment by PrachiSinghal86** [comment]
@YashKumarVerma 
- GitHub Link:- https://github.com/PrachiSinghal86/Frontend-Uplift/blob/master/error-page.html
- Preview:- https://codepen.io/prachisinghal86/pen/oNbLyPm

**Comment by YashKumarVerma** [comment]
Please use only bootstrap components.

**Comment by PrachiSinghal86** [comment]
I have tried to use bootstrap ..Can you please tell me in detail what exactly is needed to be changed.

**Comment by YashKumarVerma** [comment]
@PrachiSinghal86 check #34.

**Comment by PrachiSinghal86** [comment]
#34 is perfect and already completed so you can merge that I will work on some other issue.

**Comment by YashKumarVerma** [comment]
> #34 is perfect and already completed so you can merge that I will work on some other issue.

:+1

**Comment by YashKumarVerma** [comment]
Closing in favour of #34
