### ISSUE TITLE
New feature Proposal: Navbar

### ISSUE THREAD

**Issue by karankartikeya** [LockedUp-Coders/nostalgify#27]
Child of #18

prototype for Navbar:
https://github.com/karankartikeya/frontend-navbar.git

What are the further changes to be introduced in this?

**Comment by YashKumarVerma** [comment]
Please share a preview link / show sample on glitch / codepen / gh-pages

**Comment by YashKumarVerma** [comment]
Updated instructions regarding submission posted here:
https://github.com/LockedUp-Coders/nostalgify/issues/18

**Comment by karankartikeya** [comment]
> Please share a preview link / show sample on glitch / codepen / gh-pages

The Navbar prototype gltich link:
https://glitch.com/~abrasive-western-tax

please instruct for the changes to be introduced.

**Comment by YashKumarVerma** [comment]
Please don't use custom fonts right now. Keep it exactly like the examples given in bootstrap documentation.

Left side : Application Name
Right Side: Logout Button

another navbar with 
Left side: Application Name
Right Side: Dropdown button with list items live view profile, logout, show user image.

Keep both the navbars in same file.
Keep the navbar sticky

**Comment by karankartikeya** [comment]
@YashKumarVerma 
Updated The Navbar : 
https://codepen.io/karankartikeya/pen/XWXjWZO

Please guide how to add an image of the user ,because according to me it would need the source for the images from the Repo.

**Comment by karankartikeya** [comment]
> Please don't use custom fonts right now. Keep it exactly like the examples given in bootstrap documentation.
> 
> Left side : Application Name
> Right Side: Logout Button
> 
> another navbar with
> Left side: Application Name
> Right Side: Dropdown button with list items live view profile, logout, show user image.
> 
> Keep both the navbars in same file.
> Keep the navbar sticky

@YashKumarVerma 
Updated The Navbar :
https://codepen.io/karankartikeya/pen/XWXjWZO

Please guide how to add an image of the user ,because according to me it would need the source for the images from the Repo.

**Comment by YashKumarVerma** [comment]
Then do one thing. Link to a web image for preview. When submitting the PR in the user-interface, upload the image *we have a logo right ?* along with the code.
