### ISSUE TITLE
New feature proposal: User Profile Page Update

### ISSUE THREAD

**Issue by souravpaul8** [LockedUp-Coders/nostalgify#28]
Child of #17

Using POST request I'll accept the parameters and values that are to be changed and change those parameters in the database.
@YashKumarVerma

**Comment by souravpaul8** [comment]
@YashKumarVerma Can you confirm me few things:

1. The username corresponding to the user whose details have to be updated will be in the body (not params)
2. The body of the request will contain only properties to be changed and their corresponding value.

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma Can you confirm me few things:
> 
> 1. The username corresponding to the user whose details have to be updated will be in the body (not params)
> 2. Can a user update his username?
> 3. The body of the request will contain only properties to be changed and their corresponding value.
- yes, in the body.
- username cannot be updated.
- the body will send an object containing all details of the user. old + new.
