### ISSUE TITLE
New Feature Proposal: Logout Page

### ISSUE THREAD

**Issue by V41SH** [LockedUp-Coders/nostalgify#29]
Child of #18.

Used bootstrap modals to create a popup whenever the logout button is clicked.
This can be integrated into the user account page.

Code: https://github.com/V41SH/repo/blob/master/logout.html
Implementation: https://codepen.io/V41SH/pen/JjGKaYX

**Comment by YashKumarVerma** [comment]
You need to create a page which says, you have been logged out.

**Comment by V41SH** [comment]
Child of #18.
Created a page that shows "You have been logged out."

Code: https://github.com/V41SH/repo/blob/master/logout2.html
Implementation: https://codepen.io/V41SH/pen/xxZExXN

**Comment by YashKumarVerma** [comment]
> Child of #18.
> Created a page that shows "You have been logged out."
> 
> Code: https://github.com/V41SH/repo/blob/master/logout2.html
> Implementation: https://codepen.io/V41SH/pen/xxZExXN

Try something like

```
<div class="page-wrap d-flex flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <span class="display-1 d-block">404 !</span>
                <div class="mb-4 lead">Seems like you are lost. There's nothing in here.</div>
                <a href="/" class="btn btn-primary">Let's go back home</a>
            </div>
        </div>
    </div>
</div>
```

**Comment by V41SH** [comment]
Child of #18.
Created a page that shows "You have been logged out."

Code: https://github.com/V41SH/repo/blob/master/logout2.html
Implementation: https://codepen.io/V41SH/pen/xxZExXN

**Comment by YashKumarVerma** [comment]
- Set a proper dp.
- why bootstrap 3.5.1 ?

**Comment by V41SH** [comment]
Updated to Bootstrap 4.5.0, can be checked with the previous links itself.

**Comment by YashKumarVerma** [comment]
Good. Send a pr .
