### ISSUE TITLE
New Feature:Error Page

### ISSUE THREAD

**Issue by tejan-singh** [LockedUp-Coders/nostalgify#34]
Used Bootstrap to Create a Simple Error page with message and Button to redirect.

Github- https://github.com/tejan-singh/TheUpliftProject.git
codepen- https://codepen.io/tstejan/pen/WNrxYQO

**Comment by YashKumarVerma** [comment]
As we are not running short of time, this submission cannot be accepted as there is already an open submission for this. :disappointed: 

Saw the preview, it looks great. If the author of #26 becomes inactive / leaves the work, then this would be taken into consideration.

**Comment by YashKumarVerma** [comment]
Send a PR for this :+1:
