### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by YashKumarVerma** [LockedUp-Coders/nostalgify#4]
Update readme to name of project, removing YashKumarVerma's name

**Comment by VershaCoder** [comment]
I am working on this issue.

**Comment by vivekshah1801** [comment]
@YashKumarVerma  with reference to #6,
we should also delete 'typescript starter template' and other content related to starter template.

the content is still there in the readme.md.

**Comment by YashKumarVerma** [comment]
@vivekshah1801 send a PR.

**Comment by VershaCoder** [comment]
@vivekshah1801 Yes, you are right and also at that time I didn't notice the issue #1
You can update the content and send a PR.

**Comment by YashKumarVerma** [comment]
Why isn't there a PR for this yet ?

**Comment by VershaCoder** [comment]
@YashKumarVerma Why did you reopen this issue?

**Comment by YashKumarVerma** [comment]
@VershaCoder  check README file. Still not updated.
