### ISSUE TITLE
New test proposal :Test User Profile Updation 

### ISSUE THREAD

**Issue by harshil15999** [LockedUp-Coders/nostalgify#42]
Child of #39
@YashKumarVerma

**Comment by YashKumarVerma** [comment]
Testing is on hold. Please help in finishing off the backend items first

**Comment by harshil15999** [comment]
@YashKumarVerma  should we start this part? 
If yes please assign it to me

**Comment by harshil15999** [comment]
Why cant we use POSTMAN @YashKumarVerma ?

**Comment by YashKumarVerma** [comment]
Postman will not provide the flexibility we need in tests. :disappointed:
