### ISSUE TITLE
New feature proposal: Profile Page

### ISSUE THREAD

**Issue by VershaCoder** [LockedUp-Coders/nostalgify#45]
Child #18 

Layout Preview : [https://codepen.io/versha/pen/PoZGXjE](https://codepen.io/versha/pen/PoZGXjE)
I just created a prototype, need to do styling and code refactoring.
HTML code: [https://github.com/VershaCoder/FrontEndTasks/blob/master/ProfilePage.html](https://github.com/VershaCoder/FrontEndTasks/blob/master/ProfilePage.html)

@YashKumarVerma

**Comment by VershaCoder** [comment]
@YashKumarVerma Let me know if anything else needs to be added, will do both styling and refactoring code parallelly.

**Comment by YashKumarVerma** [comment]
Brilliant work @VershaCoder, however, there are a few recommendations:
- [x] Make the page full width, i.e. don't leave the margin on each side. (change container -> container-fluid)
- [x] Put the profile and name in a card 

(done in the preview I've shared : https://codepen.io/the-frustated-man/details/NWxbaRm)

Include the details about the user only on the left side, below the profile card. The right side where about, hobbies etc is given, there the posts about the user would come.

**Comment by VershaCoder** [comment]
Hi @YashKumarVerma 
Updated the layout.
Layout preview:https://codepen.io/versha/pen/oNbYdgN but facing issue when I am trying to resize it, getting space between card components. I have debugged it from my end but could not find anything.
Something like the below image.
![image](https://user-images.githubusercontent.com/66162944/84947696-4002c700-b108-11ea-932e-ef050fb8a81c.png)

**Comment by YashKumarVerma** [comment]
> Hi @YashKumarVerma
> Updated the layout.
> Layout preview:https://codepen.io/versha/pen/oNbYdgN but facing issue when I am trying to resize it, getting space between card components. I have debugged it from my end but could not find anything.
> Something like the below image.
> ![image](https://user-images.githubusercontent.com/66162944/84947696-4002c700-b108-11ea-932e-ef050fb8a81c.png)

Maythis this is because of of the image being too wide

**Comment by VershaCoder** [comment]
@YashKumarVerma  
Updated the profile Page:(https://codepen.io/versha/pen/vYLgQNV)
Kindly review and let me know if any change is required.

**Comment by YashKumarVerma** [comment]
Good work, send a pr pelase.

**Comment by VershaCoder** [comment]
done

**Comment by YashKumarVerma** [comment]
Thanks !
