### ISSUE TITLE
User Management Page - User Profile

### ISSUE THREAD

**Issue by Yash-R** [LockedUp-Coders/nostalgify#46]
This module handles:

 User Registration 🟢
 User login ,User logout 🟢 
 User Profile Page 🟢
@YashKumarVerma 
child of #17 
https://github.com/LockedUp-Coders/User-Management

**Comment by YashKumarVerma** [comment]
1. what's the need to doing it again when other people are already doing it @Yash-R ?
Please delete the User-Management repository, and send a pr to this repo.
