### ISSUE TITLE
 New page proposal : org : Team Listing Page

### ISSUE THREAD

**Issue by karankartikeya** [LockedUp-Coders/nostalgify#50]
child issue of #48 

Preview for the Team Listing Page:
https://codepen.io/karankartikeya/pen/QWyGGPy

Please Instruct for the changes to be made in it.

**Comment by YashKumarVerma** [comment]
something like https://bootsnipp.com/snippets/xpyz9

**Comment by karankartikeya** [comment]
> something like https://bootsnipp.com/snippets/xpyz9

Updated Preview for Team listing:
https://codepen.io/karankartikeya/pen/GRoNxGp

**Comment by YashKumarVerma** [comment]
@karankartikeya Please check #45  and have a similar design. This way we can have a consistent design throughout the site.

**Comment by karankartikeya** [comment]
> @karankartikeya Please check #45 and have a similar design. This way we can have a consistent design throughout the site.

Ok sure

**Comment by karankartikeya** [comment]
> > @karankartikeya Please check #45 and have a similar design. This way we can have a consistent design throughout the site.
> 
> Ok sure

@YashKumarVerma 
Updated the Layout according to #45 
link: https://codepen.io/karankartikeya/pen/GRoryKp

What are the other changes to be made?

**Comment by YashKumarVerma** [comment]
https://github.com/LockedUp-Coders/nostalgify/issues/48#issuecomment-647154270

**Comment by karankartikeya** [comment]
> [#48 (comment)](https://github.com/LockedUp-Coders/nostalgify/issues/48#issuecomment-647154270)


Updated the layout:
https://codepen.io/karankartikeya/pen/xxZqaGa

**Comment by YashKumarVerma** [comment]
Sorry to have confused you on this @karankartikeya , that was only an example of how the teams can be. it is not necessary that all teams will have things like science, commerce, and arts. :laughing: 

Just keep everything same and add the following changes:
- background color of card should be nothing / white
- remove buttons which says science, com.etc
- add the following details to the card:
    - date formed
    - total members

**Comment by karankartikeya** [comment]
> Sorry to have confused you on this @karankartikeya , that was only an example of how the teams can be. it is not necessary that all teams will have things like science, commerce, and arts. 
> 
> Just keep everything same and add the following changes:
> 
> * background color of card should be nothing / white
> * remove buttons which says science, com.etc
> * add the following details to the card:
>   
>   * date formed
>   * total members

Updated the page according to the instructions and removed the background color as well as image.
https://codepen.io/karankartikeya/pen/gOPmNQN

**Comment by YashKumarVerma** [comment]
Awesome ! Please send  a PR for this

**Comment by karankartikeya** [comment]
Sure,
I will send it in a moment.

**Comment by karankartikeya** [comment]
Should i close the issue or there would be change of label first?

**Comment by YashKumarVerma** [comment]
:)
