### ISSUE TITLE
New page proposal : org : Organization Profile Page

### ISSUE THREAD

**Issue by hayat-tamboli** [LockedUp-Coders/nostalgify#52]
child of #48 

- page preview : https://hayat-tamboli-user-interface.glitch.me/org/orgProfilePage.html
- HTML code : https://github.com/hayat-tamboli/user-interface/blob/master/org/orgProfilePage.html

**Comment by YashKumarVerma** [comment]
Few changes
- See the comments regarding where the content needs to go in : https://github.com/LockedUp-Coders/nostalgify/issues/45

**Comment by hayat-tamboli** [comment]
made many changes, please tell me any other changes are needed.
- code [preview](https://github.com/hayat-tamboli/user-interface/blob/master/org/orgProfilePage.html)
- page preview: https://codepen.io/hayattamboli/pen/RwroOZo

**Comment by YashKumarVerma** [comment]
Good work, but we need it similar to #45 so that the site looks as one.

**Comment by hayat-tamboli** [comment]
@YashKumarVerma  made it to look similar to #45, tell me if any changes needed.

-  HTML and page preview https://codepen.io/hayattamboli/pen/RwroOZo
