### ISSUE TITLE
New test proposal: Test User Login

### ISSUE THREAD

**Issue by tanay13** [LockedUp-Coders/nostalgify#67]
Child of #39 

@YashKumarVerma

**Comment by tanay13** [comment]
<img width="445" alt="Screenshot (118)" src="https://user-images.githubusercontent.com/61361310/85749884-d9446580-b726-11ea-99b3-1cbd3937fe95.png">
@YashKumarVerma Is this code correct for login test?

**Comment by YashKumarVerma** [comment]
looks good to me @tanay13

**Comment by tanay13** [comment]
@YashKumarVerma I am getting this error
<img width="578" alt="Screenshot (56)" src="https://user-images.githubusercontent.com/61361310/85929153-054f1a80-b8d0-11ea-9e8c-ac147b0764db.png">

**Comment by YashKumarVerma** [comment]
this is because of windows command prompt I guess. Try setting PowerShell as shell in vscode

**Comment by tanay13** [comment]
@YashKumarVerma  I tried that but same error

**Comment by YashKumarVerma** [comment]
try running mocha directly from powershell from that directory
