### ISSUE TITLE
New page proposal : org : Organization People listing Page

### ISSUE THREAD

**Issue by VershaCoder** [LockedUp-Coders/nostalgify#69]
preview link : [https://codepen.io/versha/pen/VweQjwg](https://codepen.io/versha/pen/VweQjwg)
@YashKumarVerma  let me know if any change is required.

**Comment by VershaCoder** [comment]
@YashKumarVerma any suggestion on the above preview?

**Comment by YashKumarVerma** [comment]
@VershaCoder sorry for not being clear, that page is accepted :smile: (check label)

**Comment by YashKumarVerma** [comment]
send a pr for it
